name       : signon-plugin-oauth2
version    : 0.24
release    : 1
source     :
    - https://gitlab.com/accounts-sso/signon-plugin-oauth2/-/archive/VERSION_0.24/signon-plugin-oauth2-VERSION_0.24.tar.gz : 54d6ccc255803877d37d6c510484cee2d13a087ea3f4504bc23fbf34c81e5bad
license    : LGPL-2.1-only
component  : programming
summary    : Signon OAuth 1.0 and 2.0 plugin
description: |
    This plugin for the Accounts-SSO SignOn daemon handles the OAuth 1.0 and 2.0 authentication protocols.
builddeps  :
    - pkgconfig(signond)
    - pkgconfig(Qt5Core)
rundeps :
    signon-ui
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
    # Remove files provided by kaccounts-providers for facebook
    rm -rf $installdir/etc/
